### ISSUE TITLE
Simplify inline bash script by injecting into the JSON

### ISSUE THREAD

**Issue by gavindidrichsen** [chef-partners/chef-automate-ha#4]
Suggested by Stuart in pull request #1 

Might it be worth writing a script to populate this JSON based on a placeholder value? For example:

"chef_frontend_install_script_base": "[concat(FRONTEND_SCRIPT)]"
"chef_automate_install_script_base": "[concat(AUTOMATE_SCRIPT)]"
That way the scripts themselves could live separately in more easily managed files.

**Comment by russellseymour** [comment]
@gavindidrichsen If and when you break these out into separate scripts they will just be pulled so the "inline" problem will go away

**Comment by gavindidrichsen** [comment]
Closing this as the inline scripts have been refactored now
